version: '3.3'

services:
  {{ cookiecutter.project_slug }}:
    build: .
    {% if cookiecutter.use_env== 'y' %}
    env_file:
      - ./.env
    {% endif %}
    volumes:
      - ./src:/src
    command: python3 /src/start.py

